plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.array64'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly("net.md-5:bungeecord-chat:1.21-R0.3")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}