name: Processing on push

on:
  workflow_dispatch:
  push:
  create:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move raw to formed
        run: |
          cp -r src/main/resources/META-INF/xml/ src/main/resources/grassmessage/
          cp docs/raw/* docs/formed/

      - name: Substitute $VERSION and $DOCS
        run: |
          sed -i 's|$DOCS|https://github.com/user11117s/grassmessage/blob/$REF/docs/formed|g' src/main/resources/grassmessage/*
          sed -i 's|$REF|'"$GITHUB_REF_NAME|g" src/main/resources/grassmessage/* docs/formed/*

      - name: Create tarball and remove temp folder
        run: |
          tar -czvf src/main/resources/xml.tar.gz src/main/resources/grassmessage/
          rm -rf src/main/resources/grassmessage/

      - name: Commit and push to branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated processing [skip ci]"
          file_pattern: 'src/main/resources/xml.tar.gz docs/*'
